USE AIRPORT_DB;

-- Dropping tables

DROP TABLE AIRCRAFT_STATE_VALUE;
DROP TABLE AIRCRAFT;
DROP TABLE AIRPORT;
DROP TABLE FLIGHT;
DROP TABLE COMPANY;
DROP TABLE CLIENT;
DROP TABLE AIRCRAFT_STATE;

-- Creating tables

CREATE TABLE AIRPORT
(
	ID_AIRPORT INTEGER NOT NULL CHECK(ID_AIRPORT > 0),
	AIRPORT_CODE CHAR(3) NOT NULL CHECK(AIRPORT_CODE NOT LIKE ' *' AND AIRPORT_CODE NOT LIKE '* ' AND AIRPORT_CODE <> ''),
	COUNTRY_CODE CHAR(3) NOT NULL CHECK(COUNTRY_CODE NOT LIKE ' *' AND COUNTRY_CODE NOT LIKE '* ' AND COUNTRY_CODE <> ''),
	CITY VARCHAR(50) CHECK(CITY NOT LIKE ' *' AND CITY NOT LIKE '* ' AND CITY <> ''),
	PRIMARY KEY (ID_AIRPORT),
	UNIQUE (AIRPORT_CODE)
);

CREATE TABLE FLIGHT
(
	ID_FLIGHT INTEGER NOT NULL CHECK(ID_FLIGHT > 0),
	FLIGHT_NUMBER VARCHAR(10) NOT NULL CHECK(FLIGHT_NUMBER NOT LIKE ' *' AND FLIGHT_NUMBER NOT LIKE '* ' AND FLIGHT_NUMBER <> ''),
	PLANNED_DEPARTURE_TIME TIME NOT NULL,
	PLANNED_ARRIVAL_TIME TIME NOT NULL,
	PRIMARY KEY (ID_FLIGHT),
	UNIQUE (FLIGHT_NUMBER)
);

CREATE TABLE COMPANY
(
	ID_COMPANY INTEGER NOT NULL CHECK(ID_COMPANY > 0),
	REGISTRATION_NUMBER VARCHAR(20) NOT NULL CHECK(REGISTRATION_NUMBER NOT LIKE ' *' AND REGISTRATION_NUMBER NOT LIKE '* ' AND REGISTRATION_NUMBER <> ''),
	COMPANY_NAME VARCHAR(50) CHECK(COMPANY_NAME NOT LIKE ' *' AND COMPANY_NAME NOT LIKE '* ' AND COMPANY_NAME <> ''),
	PRIMARY KEY (ID_COMPANY),
	UNIQUE (REGISTRATION_NUMBER)
);

CREATE TABLE CLIENT
(
	ID_CLIENT INTEGER NOT NULL CHECK(ID_CLIENT > 0),
	CLIENT_NAME VARCHAR(30) NOT NULL CHECK(CLIENT_NAME NOT LIKE ' *' AND CLIENT_NAME NOT LIKE '* ' AND CLIENT_NAME <> ''),
	PASSPORT_NUMBER VARCHAR(10) NOT NULL CHECK(PASSPORT_NUMBER NOT LIKE ' *' AND PASSPORT_NUMBER NOT LIKE '* ' AND PASSPORT_NUMBER <> ''),
	E_MAIL VARCHAR(30) CHECK(E_MAIL NOT LIKE ' *' AND E_MAIL NOT LIKE '* ' AND E_MAIL <> ''),
	TELEPHONE_NUMBER VARCHAR(15) CHECK(TELEPHONE_NUMBER NOT LIKE ' *' AND TELEPHONE_NUMBER NOT LIKE '* ' AND TELEPHONE_NUMBER <> ''),
	PRIMARY KEY (ID_CLIENT),
	UNIQUE (CLIENT_NAME, PASSPORT_NUMBER)
);

CREATE TABLE AIRCRAFT_STATE
(
	ID_STATE INTEGER NOT NULL CHECK(ID_STATE > 0),
	STATE_TITLE VARCHAR(30) NOT NULL CHECK(STATE_TITLE NOT LIKE ' *' AND STATE_TITLE NOT LIKE '* ' AND STATE_TITLE <> ''),
	PRIMARY KEY (ID_STATE),
	UNIQUE (STATE_TITLE)
);

CREATE TABLE AIRCRAFT
(
	ID_AIRCRAFT INTEGER NOT NULL CHECK(ID_AIRCRAFT > 0),
	AIRCRAFT_TAIL_NUMBER VARCHAR(30) NOT NULL CHECK(AIRCRAFT_TAIL_NUMBER NOT LIKE ' *' AND AIRCRAFT_TAIL_NUMBER NOT LIKE '* ' AND AIRCRAFT_TAIL_NUMBER <> ''),
	AIRPORT_ID INTEGER NOT NULL CHECK(AIRPORT_ID > 0),
	COMPANY_ID INTEGER NOT NULL CHECK(COMPANY_ID > 0),
	AIRCRAFT_TYPE VARCHAR(30) NOT NULL CHECK(AIRCRAFT_TYPE NOT LIKE ' *' AND AIRCRAFT_TYPE NOT LIKE '* ' AND AIRCRAFT_TYPE <> ''),
	AIRCRAFT_CAPACITY INTEGER CHECK(AIRCRAFT_CAPACITY > 0),
	PRIMARY KEY (ID_AIRCRAFT),
	UNIQUE (AIRCRAFT_TAIL_NUMBER),
	FOREIGN KEY (AIRPORT_ID) REFERENCES AIRPORT(ID_AIRPORT) ON UPDATE CASCADE,
	FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY(ID_COMPANY) ON UPDATE CASCADE
);

CREATE TABLE AIRCRAFT_STATE_VALUE
(
	AIRCRAFT_ID INTEGER NOT NULL CHECK(AIRCRAFT_ID > 0),
	STATE_ID INTEGER NOT NULL CHECK(STATE_ID > 0),
	PRIMARY KEY (AIRCRAFT_ID, STATE_ID),
	FOREIGN KEY (AIRCRAFT_ID) REFERENCES AIRCRAFT(ID_AIRCRAFT) ON UPDATE CASCADE,
	FOREIGN KEY (STATE_ID) REFERENCES AIRCRAFT_STATE(ID_STATE) ON UPDATE CASCADE
);